name: Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '23 7 * * 1'

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    permissions:
      security-events: write
      actions: read
      contents: write
      checks: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin' ]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - run: mvn -B -ntp test

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          args: --baseline,qodana.sarif.json
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
