# This workflow will build a Java project with Maven,
#  and cache/restore any dependencies to improve the workflow execution time
# For more information see:
#  https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Continuous Integration for Docx4J

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '23 7 * * 1'

permissions:
  pull-requests: read

jobs:
  ci:
    continue-on-error: true
    name: Continuous Integration
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        docx4j:
          # - 11.1.0
          # - 11.1.2
          # - 11.1.3
          # - 11.1.7
          # - 11.1.8
          # - 11.2.5
          # - 11.2.8
          # - 11.2.9
          # - 11.3.2
          # - 11.4.5
          # - 11.4.6
          # - 11.4.7
          # - 11.4.8
          - 11.4.9
          - 11.4.10
          - 11.4.11

    runs-on: ${{ matrix.os }}

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'

      - run: mvn -B -ntp test -Ddocx4j.version="${{ matrix.docx4j }}"
